apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: nginx-warehouse
  namespace: nginx-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
    - image:
        repoURL: my-harbor-core.harbor.svc.cluster.local/library/nginx
        allowTags: ".*"
        discoveryLimit: 10
    - git:
        repoURL: https://github.com/Itsjoses/nginx-argocd-kargo.git
